#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup Values
DOLI_ADMIN_LOGIN = data.get("DOLI_ADMIN_LOGIN", "admin")
DOLI_ADMIN_PASSWORD = data.get("DOLI_ADMIN_PASSWORD", "admin")

agent.set_env("DOLI_ADMIN_LOGIN", DOLI_ADMIN_LOGIN)
agent.set_env("DOLI_ADMIN_PASSWORD", DOLI_ADMIN_PASSWORD)

agent.dump_env()
