#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import os
import sys

request = json.load(sys.stdin)

ldap_domain = request.get("ldap_domain")
# Bind the new domain, overriding previous values (unbind)
if ldap_domain:
    agent.bind_user_domains([ldap_domain])
else:
    agent.bind_user_domains([])