#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

def generate_random_password():
    return secrets.token_urlsafe(16)

MARIA_ROOT_PASSWORD = generate_random_password()
MARIA_DATABASE = data.get('MARIADB_DATABASE', 'dolibarr')
MARIA_USER = data.get('MARIADB_USER', 'dolibarr')
MARIA_PASSWORD = generate_random_password()
MARIA_AUTO_UPGRADE = 1
db_config = {
    'MARIADB_ROOT_PASSWORD': MARIA_ROOT_PASSWORD,
    'MARIADB_DATABASE': MARIA_DATABASE,
    'MARIADB_USER': MARIA_USER,
    'MARIADB_PASSWORD': MARIA_PASSWORD,
    'MARIADB_AUTO_UPGRADE': MARIA_AUTO_UPGRADE,
}
agent.write_envfile("database.env", db_config)


dolibarr_config = {
    'DOLI_DB_TYPE': 'mysqli',
    'DOLI_DB_HOST': 'mariadb-app',
    'DOLI_DB_USER': 'root',
    'DOLI_DB_PASSWORD': MARIA_ROOT_PASSWORD,
    'DOLI_DB_HOST_PORT': 3306,
    'DOLI_DB_NAME': MARIA_DATABASE,
}
agent.write_envfile("dolibarr-db.env", dolibarr_config)

agent.dump_env()
